# LOCAL SETTINGS

# Language for LLM and STT prompts
language: 'en'

# auto transcribe messages if received
##WARNING: Be aware that every audio (-length) gets turned into text.
auto_transcribe: false

# auto-summarize if text has more than the configured amount of words
auto_summary: true
auto_summary_words: 80

storage:
  # path for matrix-commander store
  store_path: '/data/store'
  # path for all received media files (named after their event_id)
  media_path: '/data/media'
  # path for matrix-commander credentials 
  # "/data" for docker container
  # "/home/username/.local/share/matrix-commander" for normal install
  credentials_path: '/data'

# Speech-To-Text Models
stt:
# stt api source
# choose between 'whisper-asr' (default), 'localai', and more (work in progress)
  source: 'whisper-asr'
  host: 'localhost'
  port: 9000

# Language Models
llm:
# llm api source
# choose between 'ollama' (default), 'localai', and more (work in progress)
  source: 'ollama'
  host: 'localhost'
  port: 11434
  models:
   - prefix: '#eva'
     model_name: 'eva-german:latest'
     language: 'de'
   - prefix: '#ml'
     model_name: 'mistral-german:latest'
     language: 'de'
   - prefix: '#sl'
     model_name: 'stablelm:12b'
     language: 'de'
   - prefix: '#text'
     model_name: 'llama3:latest'
     language: 'en'
   - prefix: '#code'
     model_name: 'starcoder2:7b'
     language: 'en'

# Multimodal Models (Image + Text)
lmm:
# lmm api source
# only tested with 'ollama', 'localai' could work
  source: 'ollama'
  host: 'localhost'
  port: 11434
  models:
   - prefix: '#lv'
     model_name: 'llava:latest'
     language: 'en'
   - prefix: '#bv'
     model_name: 'bakllava:latest'
     language: 'en'
   - prefix: '#md'
     model_name: 'moondream:latest'
     language: 'en'
  
commands:
  help: '#help'
  visual_assist: '#cc'
  transcribe: '#cc'
  summarize: '#sum'

# Logging setup
logging:
  # Logging level
  # Allowed levels are 'INFO', 'WARNING', 'ERROR', 'DEBUG'
  # where DEBUG is most verbose
  level: INFO
  # Configure logging to a file
  file_logging:
    # Whether logging to a file is enabled
    enabled: false
    # The path to the file to log to. May be relative or absolute
    filepath: bot.log
  # Configure logging to the console output
  console_logging:
    # Whether logging to the console is enabled
    enabled: true
